import NavBar from '@/components/NavBar'
import Head from 'next/head'
import Image from 'next/image'
import Main from '@/components/Main'
import About from '@/components/About'


export default function Home() {
  return (
    <>
      <Head>
        <title>Prashant Bhushal</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar/>
      <Main/>
      <About/>
    </>
  )
}
